# Generated by Django 4.1.2 on 2022-11-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0002_alter_question_pub_date_alter_question_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=100, verbose_name='Enquete'),
        ),
    ]
