# Generated by Django 4.1.2 on 2022-11-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0003_alter_question_question_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
            ],
        ),
    ]
