# Generated by Django 4.1.2 on 2022-11-29 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0005_alter_question_pub_date_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 14, 38, 46, 592557), verbose_name='Data de publicação'),
        ),
    ]
