# Generated by Django 4.1.2 on 2022-11-29 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0008_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 18, 4, 44, 873816, tzinfo=datetime.timezone.utc), verbose_name='Data de publicação'),
        ),
    ]
