# Generated by Django 4.1.2 on 2022-11-29 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0011_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 15, 13, 58, 681370), verbose_name='Data de publicação'),
        ),
    ]
