# Generated by Django 4.1.2 on 2022-12-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=None, upload_to='profile', verbose_name='Imagem do perfil'),
        ),
    ]
